version: 0.2

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

env:
  parameter-store:
    NPM_TOKEN: "/sauerkraut/npm/token"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

phases:
  install:
    commands:
      - echo "install dependancies..."
      - npm install
    finally:
      - echo "...installed dependancies"

  pre_build:
    commands:
      - echo "node version"
      - node --version

      - echo "npm version"
      - npm --version

      - echo "npm token"
      - echo "$NPM_TOKEN"

      - VERSION=$(node -p "require('./package.json').version")
      - echo "package version"
      - echo "$VERSION"

      - echo "create .npmrc file..."
      # Note: Must reference the file system root ~/.npmrc and not the copy
      # associated to the project
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - echo "...createed .npmrc file"
      - cat ~/.npmrc

      - echo "root files"
      - echo $(ls)

  build:
    commands:
      - echo "create package..."
      - npm run build
      - npm pack

      # Rename a copy of the convoluted named package to a simple name with just
      # the version release value.
      # Example: devon-church-sauerkraut-1.0.0.tgz ---> 1.0.0.tgz
      # Note: we use `cp` not `mv` as we still need the originally named package
      # when running `npm publish`.
      - cp ./devon-church-sauerkraut-$VERSION.tgz ./$VERSION.tgz
    finally:
      - echo "...created package"

  post_build:
    commands:
      - echo "publish to npm..."
      - npm publish --access="public"

      - echo "publish to s3..."
      - aws s3 cp s3://sauerkraut/$VERSION.tgz ./$VERSION.tgz
    finally:
      - echo "...published to npm"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

cache:
  paths:
    - "node_modules/**/*"
